#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE_DIR="${CANOPY_JIMS_SOURCE_DIR:-$ROOT_DIR/../fpsshooterserver}"
DESTINATION="${1:-}"
MULTIPLAYER_URL="${CANOPY_JIMS_SERVER_URL:-wss://jimsmowingandlawncare.up.railway.app/}"

if [[ -z "$DESTINATION" ]]; then
  echo "Usage: stage-jims-client.sh <destination>"
  exit 1
fi

required_files=(
  index.html
  legal.html
  maps.js
  core.js
  client-config.js
  dust2-minimap.png
  jim-favicon.png
  jims-mowing-logo.png
  sw.js
)

for file in "${required_files[@]}"; do
  if [[ ! -f "$SOURCE_DIR/$file" ]]; then
    echo "Missing Jim's Mowing client file: $SOURCE_DIR/$file"
    exit 1
  fi
done
if [[ ! -d "$SOURCE_DIR/assets" ]]; then
  echo "Missing Jim's Mowing assets directory: $SOURCE_DIR/assets"
  exit 1
fi

case "$MULTIPLAYER_URL" in
  ws://*|wss://*) ;;
  *)
    echo "CANOPY_JIMS_SERVER_URL must use ws:// or wss://"
    exit 1
    ;;
esac

rm -rf "$DESTINATION"
mkdir -p "$DESTINATION"
for file in "${required_files[@]}"; do
  ditto "$SOURCE_DIR/$file" "$DESTINATION/$file"
done
ditto "$SOURCE_DIR/assets" "$DESTINATION/assets"

escaped_url="${MULTIPLAYER_URL//\\/\\\\}"
escaped_url="${escaped_url//\"/\\\"}"
cat > "$DESTINATION/client-config.js" <<EOF
// Generated by Canopy's native build. Do not edit this staged copy.
window.JIMS_CLIENT_CONFIG = Object.freeze({
  multiplayerUrl: "$escaped_url",
  serviceWorkerEnabled: false
});
EOF

echo "Staged Jim's Mowing client from: $SOURCE_DIR"
echo "Multiplayer endpoint: $MULTIPLAYER_URL"
